////////////////////////////////////////////////////////////////////////
// Class:       MyPandoraAnalyzer
// Module Type: analyzer
// File:        MyPandoraAnalyzer_module.cc
//
// Generated at Tue Nov 10 13:06:09 2015 by Wesley Ketchum using artmod
// from cetpkgsupport v1_08_07.
////////////////////////////////////////////////////////////////////////

#include "art/Framework/Core/EDAnalyzer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "art/Utilities/InputTag.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"

#include "art/Framework/Services/Optional/TFileService.h"

#include "TTree.h"

#include "../MyPandoraAnalysis/MyPandoraAnalysis.hh"

namespace test {
  class MyPandoraAnalyzer;
}

class test::MyPandoraAnalyzer : public art::EDAnalyzer {
public:
  explicit MyPandoraAnalyzer(fhicl::ParameterSet const & p);
  // The destructor generated by the compiler is fine for classes
  // without bare pointers or other resource use.

  // Plugins should not be copied or assigned.
  MyPandoraAnalyzer(MyPandoraAnalyzer const &) = delete;
  MyPandoraAnalyzer(MyPandoraAnalyzer &&) = delete;
  MyPandoraAnalyzer & operator = (MyPandoraAnalyzer const &) = delete;
  MyPandoraAnalyzer & operator = (MyPandoraAnalyzer &&) = delete;

  // Required functions.
  void analyze(art::Event const & e) override;

  // Selected optional functions.
  void reconfigure(fhicl::ParameterSet const & p) override;

private:

  // Declare member data here.
  test::MyPandoraAnalysis fMyAnalysisObj;
  
};


test::MyPandoraAnalyzer::MyPandoraAnalyzer(fhicl::ParameterSet const & p)
  :
  EDAnalyzer(p)  // ,
 // More initializers here.
{
  art::ServiceHandle<art::TFileService> tfs;
  fMyAnalysisObj.SetupOutputTree(tfs->make<TTree>("myanatree","MyAnalysis Tree"));
}

void test::MyPandoraAnalyzer::analyze(art::Event const & e)
{
  fMyAnalysisObj.RunAnalysis();
}

void test::MyPandoraAnalyzer::reconfigure(fhicl::ParameterSet const & p)
{
  // Implementation of optional member function here.
}

DEFINE_ART_MODULE(test::MyPandoraAnalyzer)
